-- AlterTable
ALTER TABLE `Admin` ADD COLUMN `idNumber` INTEGER NULL;

-- AlterTable
ALTER TABLE `Expense` ADD COLUMN `reason` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED') NOT NULL DEFAULT 'PENDING';
